# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: end-of-file-fixer
    exclude: ^(docs/|hypernetx.egg-info/)
  - id: trailing-whitespace
    exclude: ^(docs/|hypernetx.egg-info/)
  - id: check-merge-conflict
  - id: no-commit-to-branch
    args: ['--branch', 'master'] # blocks master commits.  To bypass do git commit --allow-empty

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        exclude: ^(docs/|hypernetx.egg-info/)

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        exclude: (?x)(docs/|tests/)
        args: [--no-strict-optional, --ignore-missing-imports]
